### ISSUE TITLE
Any plans of going to postgres 0.16.x

### ISSUE THREAD

**Issue by hilmer** [robconery/moebius#113]

**Comment by robconery** [comment]
I should probably archive this repo I haven't worked on it in years. It's nearly impossible to work with a driver that is permanently held < 1.0

**Comment by cpursley** [comment]
I use it an an active project and vastly prefer it over ecto. Anything I can do to help maintain it?

**Comment by hilmer** [comment]
Yes, it would be a shame to let it wither and die. I have just replaced all my ecto with moebius, it is so much nicer.
Not, sure if I can help maintain though.

**Comment by cpursley** [comment]
I forgot that I had access to make changes on this repo.

@hilmer ~ I went ahead and bumped up postgrex: 

https://github.com/robconery/moebius/commit/5379b191bae27a71c812140e4c581300e5dbe57d

**Comment by cpursley** [comment]
@robconery would it be possible for me to also have maintainer access on hex.pm so that I can bump up releases?

**Comment by hilmer** [comment]
@cpursley Thank you!!
