### ISSUE TITLE
How do I ACTUALLY use it

### ISSUE THREAD

**Issue by codefist** [robconery/moebius#115]
![image](https://user-images.githubusercontent.com/16125676/231038789-1afc3e3c-6637-4724-acf4-c2b704b24bbd.png)

**Comment by codefist** [comment]
config :moebius,
    connection: [
    hostname: "postgres",
    username: "postgres",
    password: "postgres",
    database: "moebius"
  ],
  scripts: "test/db"

**Comment by codefist** [comment]
defmodule Neo.Read do
  use Moebius.Database
end

![image](https://user-images.githubusercontent.com/16125676/231039060-4cb13542-4ae8-430d-b1c4-fa4d5c9e2c30.png)

**Comment by codefist** [comment]
found it, you have this in the readme:
{MyApp.Db, [Moebius.get_connection]}
it should be:
{MyApp.Db, Moebius.get_connection}

**Comment by codefist** [comment]
err, now another problem:
![image](https://user-images.githubusercontent.com/16125676/231039939-5660386b-ca7c-41af-9224-d371d1b9a1fc.png)

Can you please try to set this up on a fresh phoenix project and document what you need to do to use it.

**Comment by cpursley** [comment]
Hi @codefist - looks like you were able to figure out how to get everything running?

**Comment by codefist** [comment]
> Hi @codefist - looks like you were able to figure out how to get everything running?

Yes, but you should fix the readme as I say above.
{MyApp.Db, [Moebius.get_connection]} is wrong.
The readme is pretty scattered, took me a while to understand.

**Comment by cpursley** [comment]
@codefist feel free to put in a pull request to fix the readme or any other cleanup.
