### ISSUE TITLE
named parameters support

### ISSUE THREAD

**Issue by plamb** [robconery/moebius#39]
Thinking a bit out loud here:

Instead of having to keep track of parameter positions in a query it would be useful to use named parameters, i.e.

``` sql
SELECT * FROM users WHERE lname = :lname AND fname = :fname
```

Then you'd have a hash of params, in any order and may have unused entries, that would be combined  for the result.

``` ruby
%{id: 1234, fname: "Charlie", lname: "Brown", dog: "snoopy", adversary: "Lucy"}
```

Under the covers this would get converted to a tuple that can then run as a normal pg query:

``` ruby
{"SELECT * FROM users WHERE lname = $1 AND fname = $2",["Brown", "Charlie"]}
```

Here's a rather terse way of doing it that I banged out this afternoon. 

``` ruby
  def convert_named_params(query, opts) do
    named_param_regex = ~r/:(\w+)/i

    # do the regex and convert the results to a map of {:atom, string}
    m = Regex.scan(named_param_regex, query)
    |> Enum.map(fn([v, a]) -> {String.to_atom(a), v} end)

    # replace the named params in the query with $1...$n
    {q, _} = Enum.reduce(m, {query, 1}, fn({_,v}, {q, i}) -> {String.replace(q, v, "$#{i}"), i + 1 } end)

    # create a list of options to be used as params
    o = Enum.map(m, fn({k,_}) -> opts[k]  end)

    {q, o}
  end
```

**Comment by robconery** [comment]
I like it - we could do this for the SQL files as well. Want to keep rolling and spin a PR?

**Comment by plamb** [comment]
I'll work on a PR, it's going to be next week though, things are a bit crazy right now.

**Comment by robconery** [comment]
Closing for now - feel free to reopen.
