### ISSUE TITLE
Moebius.Query.with/1 won't compile with Elixir 1.2

### ISSUE THREAD

**Issue by dovadi** [robconery/moebius#45]
Using Moebius in a project will result in the following error during compilation with Elixir 1.2

```
cannot import Moebius.Query.with/1 because it conflicts with Elixir special forms
    (elixir) src/elixir_import.erl:92: :elixir_import.calculate/6
    (elixir) src/elixir_import.erl:22: :elixir_import.import/4
```

Elixir 1.2 added the with special form to match on multiple expressions

```
with {:ok, contents} <- File.read("my_file.ex"),
     {res, binding} <- Code.eval_string(contents),
     do: {:ok, res}
```

Is renaming Moebius.Query.with/1 the best option (like they did in Pavlov , see https://github.com/sproutapp/pavlov/pull/49)?

**Comment by plamb** [comment]
I was just looking at this too. Thinking that maybe just renaming it to with_table?

**Comment by robconery** [comment]
This is fixed with v2
