### ISSUE TITLE
Transaction API question

### ISSUE THREAD

**Issue by 0x6e6562** [robconery/moebius#52]
I'm trying to use the the transaction API:

``` elixir
transaction fn(tx) ->
   "insert into x(text) values('foo');" |> Moebius.Db.run(tx)
   "select * from x limit 1;" |> Moebius.Db.run(tx)
end
```

But this is causing the underlying gen_server to crash:

```
** (exit) exited in: :gen_server.call(My.Db, {:checkout, #Reference<0.0.2.364>, true, 5000}, 5000)
```

For note, if I run the same code without the transaction fun/1 wrapper, it seems to execute just fine:

``` elixir
"insert into x(text) values('foo');" |> Moebius.Db.run
"select * from x limit 1;" |> Moebius.Db.run
```

Is there something obvious that I'm doing wrong?

**Comment by robconery** [comment]
The error seems to be from My.Db not being there. What is that?

**Comment by 0x6e6562** [comment]
Here's the definition of My.Db:

``` elixir
defmodule My.Db do
  use Moebius.Database
  import Moebius.Query

  # This blows up like this:
  # ** (exit) exited in: :gen_server.call(My.Db, {:checkout, #Reference<0.0.4.534>, true, 5000}, 5000)
  #  ** (EXIT) no process
  def x do
    transaction fn(tx) ->
        "insert into x(text) values('foo');" |> Moebius.Db.run(tx)
        "select * from x limit 1;" |> Moebius.Db.run(tx)
    end
  end

  # But this executes just fine
  def y do
    function(:a_new_x, "x") |> Moebius.Db.run
  end

  # This executes fine as well
  def z do
    "select * from x limit 1;" |> Moebius.Db.run
  end

end
```

**Comment by robconery** [comment]
Ahh - yeah this would mess things up wouldn't it :). Whenever you `use Moebius.Database` that module becomes the thing you query against. So, in this case, you would use `My.Db.run` in all cases. The default database is there just if you're being lazy. Does that make sense?

Also, make sure that `My.Db` is added to your supervision tree and is started...

**Comment by 0x6e6562** [comment]
Perfect!

Using the supervised and started `My.Db` process, the following works:

``` elixir
defmodule My.Db do
  use Moebius.Database
  import Moebius.Query
  def x do
    transaction fn(tx) ->
        "insert into x(text) values('foo');" |> My.Db.run(tx)
        "select * from x limit 1;" |> My.Db.run(tx)
    end
  end
end
```

I've also tested the rollback by executing a valid followed by an invalid SQL statement, so all is good.

Many thanks for your help :-)

**Comment by robconery** [comment]
You're welcome!
