### ISSUE TITLE
Provide a way to run more complex scripts

### ISSUE THREAD

**Issue by hubertlepicki** [robconery/moebius#56]
I'd like to build a simple up/down migrations thing for moebius. I have a prototype working. I know @robconery does not likes migrations, well I do and probably many others too. I find it useful when working with a team of devs, mostly. So I intend it to be separate library.

I figured so far that I can put my migrations into scripts/migrations/some_migration_timestamp_up.sql etc. This is working and I ma using

```
Moebius.Query.sql_file(:"migrations/#{timestamp}_up") |> Moebius.Db.run
```

to run the migration. Then I update database table with list of applied migrations if the above succeeds. When I rollback migration I do the other way around: remove applied migration from the lsit.

The problem is: I am limited to one SQL command per file. If I try to add multiple ones, I get:

```
{:error, "cannot insert multiple commands into a prepared statement"}
```

I don't even need it to be prepared statement.

Is there a way to dump raw SQL to Moebius.Db somehow?

**Comment by amagdas** [comment]
Moebius.psql I think is the only way for now.

**Comment by hubertlepicki** [comment]
@amagdas found it! Thanks for the tip!

https://github.com/robconery/moebius/blob/09585f94afacbd428fd28665ca87bcc480f5d5f5/lib/moebius.ex#L18

But it won't specify all connection options from what I can see. I think I'll write similar function in my lib so there's nothing needed to be done on moebius side of things.

**Comment by robconery** [comment]
The problem is the driver - it won't do multiple prepared statements. PSQL is the only way. Also - Ecto's migrations are pretty good - you could use that :).
