### ISSUE TITLE
Timex version

### ISSUE THREAD

**Issue by pyladune** [robconery/moebius#57]
Does that mean we should step back to 1.1.0 of timex  with last version of moebius ?

Failed to use "timex" because
  moebius (version 2.0.0) requires ~> 1.0.0
  Locked to 2.1.4 in your mix.lock

**Comment by robconery** [comment]
I don't understand what the problem here is.

**Comment by nurugger07** [comment]
Do we need to bump the timex version?

**Comment by pyladune** [comment]
the problem is that we use timex 2.1.4
and mix deps.get complains because says that moebius requires 1.0.0

 defp deps do
    [{:postgrex, "~> 0.11.0"},
     {:poolboy, "~> 1.5"},
     {:timex, "~> 1.0.0"},
     {:inflex, "~> 1.5.0"},
     {:poison, "~> 2.0.1", optional: true},
     {:ex_doc, "~> 0.11.2", only: [:dev, :docs]},
     {:earmark, "~> 0.2.0", only: [:dev, :docs]},
     {:credo, "~> 0.2.5", only: [:dev, :test]}]
  end

**Comment by robconery** [comment]
Can you please spell out the problem for me? Moebius does not require 1.1.0, we use 2+. Can you please add some detail to this thread - we're 5 deep and I have no idea what you want me to do.

**Comment by nurugger07** [comment]
We just need to update the timex version. Currently moebius is using 1.0

https://github.com/robconery/moebius/blob/master/mix.exs#L35

**Comment by robconery** [comment]
Holy crap! My mistake sorry about that - I could _swear_ I had upgraded it to 2+. Ugh... I think we should make @xivSolutions do it...

**Comment by nurugger07** [comment]
+1 to @xivSolutions doing it :)

**Comment by pyladune** [comment]
thanks and sorry not have been clear enough to explain it from start

**Comment by pyladune** [comment]
no moves on that ??

**Comment by xivSolutions** [comment]
@pyladune  Sorry all - I somehow missed @robconery assigning this to me lol. I'll get right on it after work today.

**Comment by xivSolutions** [comment]
Indeed, number of breaking changes in Timex 2.1. I'll have this handled tonight or sometime tomorrow, sorry.

**Comment by xivSolutions** [comment]
Updated. See PR.

**Comment by nurugger07** [comment]
@robconery I believe this issue has been resolved and can be closed. Thanks @xivSolutions!
