### ISSUE TITLE
No function clause matching in Moebius.Extensions.DateExtension.decode/4

### ISSUE THREAD

**Issue by nurugger07** [robconery/moebius#61]
Getting an issue when the `%Postgrex.TypeInfo{type: "timestamp"}`. There isn't a match on that. I can add the fix but wanted to check with @xivSolutions first.

``` bash
** (FunctionClauseError) no function clause matching in Moebius.Extensions.DateExtension.decode/4
           (moebius) lib/moebius/extensions/date_extension.ex:47: Moebius.Extensions.DateExtension.decode(%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [], input: "timestamp_in", oid: 1114, output: "timestamp_out", receive: "timestamp_recv", send: "timestamp_send", type: "timestamp"}, <<0, 1, 215, 143, 95, 251, 70, 53>>, 172079, nil)
          (postgrex) lib/postgrex/query.ex:118: DBConnection.Query.Postgrex.Query.decode_row/4
          (postgrex) lib/postgrex/query.ex:109: DBConnection.Query.Postgrex.Query.do_decode/5
          (postgrex) lib/postgrex/query.ex:74: DBConnection.Query.Postgrex.Query.decode/3
     (db_connection) lib/db_connection.ex:423: DBConnection.query/4
          (postgrex) lib/postgrex.ex:111: Postgrex.query/4
           (moebius) lib/moebius/database.ex:236: Moebius.Database.execute/1
    (authentication) lib/moebius/database.ex:38: Authentication.Database.run/1
```

**Comment by xivSolutions** [comment]
I find it odd this hasn't created trouble before now... @nurugger07 I won't be able to look at this until at least tonight. If you have the fix, and want to get it up there, do so. I can then try to break it ;-)

Otherwise I'll see what I can figure out. My only concern I guess is that this was something intentional, which has somehow become broken, or just an oversight back when @robconery was experimenting putting together the custom date extensions.

**Comment by xivSolutions** [comment]
@nurugger07  - I think your suggested fix of modifying the function signature is the simplest, most sensible fix. My understanding is that the use of `timestamp` is less then ideal in the majority of use cases, but we should probably cover it. 

It would surprise me not at all to learn that @robconery made a tactical decision not to handle that type specifically, given his convictions about dates and timezones (which I share). :trollface: 

I believe the decoding itself is valid in either case, so doing:

``` elixir
def decode(%Postgrex.TypeInfo{type: timestamp},<<microsecs :: int64>>, _, _) when timestamp in ["timestamptz", "timestamp"] do
```

should do it. I Think. I did it locally, and added a test that passes.

**Comment by nurugger07** [comment]
This can be closed now. I fixed it with https://github.com/robconery/moebius/pull/62
