### ISSUE TITLE
Atom keys of JSONB returned by function

### ISSUE THREAD

**Issue by 0x6e6562** [robconery/moebius#65]
I've got a function that that returns JSONB and the keys are bound as strings. Is there a way to get Moebius to return the keys as atoms, or is it a concern for the application to convert the keys to atoms?

**Comment by 0x6e6562** [comment]
For note, reading #48, it would appear that Moebius uses atoms by default - is this not the case for custom functions returning JSONB objects?

**Comment by robconery** [comment]
If you use the document abstraction then we turn the keys into atoms. Otherwise, the column is translated at JSON - and a correct translation of JSON is to have keys as strings.

**Comment by 0x6e6562** [comment]
I'm constructing the JSON as a view in the DB (using `jsonb_build_object(...)`) rather than using JSONB columns. Is there an easy way to mimic the behavior of the document abstraction and override the default for JSON? At the moment I am post-processing the returned JSON to convert the keys to atoms, but given that this already exists in Moebius, I was wondering if I could do it at this level.

Or would this require a patch?

**Comment by robconery** [comment]
Yeah - try piping on `Moebius.Transformer.from_json` - that should turn the string keys to atoms...

**Comment by 0x6e6562** [comment]
That looks promising!

However, I'm having difficulty understanding how the API works at this point. So I'm trying to change this:

```
function(:my_func, id) |> My.Db.run
```

to this:

```
function(:my_func, id) |> My.Db.execute |> Moebius.Transformer.from_json
```

because all of the `My.Db.run` function heads that match on `%Moebius.QueryCommand{}` appear to have hard coded a follow on pipe to `Moebius.Transformer.to_list`.

However `My.Db.execute/1` is not exposed.

Should I be using the API in a different way (e.g. not using the module alias)?

**Comment by robconery** [comment]
Oh - right. That won't work as it expects certain fields to be there. Here's another thought: maybe return the value as a string. You can set the field to be ::varchar(5000) or something. Then, in your code, you can use `Poision.decode!(val, :atomize_keys!)`.

**Comment by 0x6e6562** [comment]
Yes, that would work as well. Potentially I could reconsider constructing the JSON in Postgres and instead deliver regular DB rows, have Moebius atomize them by default and then construct the JSON blob in the app.

**Comment by 0x6e6562** [comment]
For anybody following this thread, by casting the JSONB to TEXT, the following worked for me with Poison 2.0.1:

```
Poison.decode!(val, keys: :atoms)
```

**Comment by 0x6e6562** [comment]
I think we should mark this issue as closed now - many thanks for your help @robconery :-)
