### ISSUE TITLE
Is test_schema.sql used anywhere in this project

### ISSUE THREAD

**Issue by CrowdHailer** [robconery/moebius#66]
Hi, 

I am trying to learn how to use Moebius. It turns out that to do this I have to learn a good bit more about SQL and how to do migrations etc.

I am curious as to why the SQL in `test_helper.exs` is duplicated in `test_schema.sql`. I cannot find any piece of code that uses `test_schema.sql`. Is it used anywhere?

**Comment by robconery** [comment]
That's me being sloppy :). We used to run that file directly with `psql` before each test run, but it turned out to be a bit easier to pipe the command as you see in `test_helper`. 

I don't understand the SQL comment - do you mean that you need to learn how to create tables etc?

**Comment by CrowdHailer** [comment]
In essence yes. I am coming from Ruby where I previously used sequel.rb which handled creating tables etc.

Starting with Moebius for me was quite slow because the docs don't suggest how to create tables etc. The docs just start querying some tables that are assumed to exist. Makes it a bit unapproachable for users with backgrounds similar to mine.

I'm not sure how I would change this and I like the fact that moebius is very focused but  thought I would flag it.

I tried copying that script in test schema and running it with Db.run wasted a bit of time there before I discovered it needed to be run with `Moebius.run_with_psql`

**Comment by CrowdHailer** [comment]
Perhaps a small example on how to set up tables might be nice. even if it just works as an example on how to use run_with_psql.

**Comment by robconery** [comment]
I might suggest two approaches:
- knuckle down and spend the day reading up on SQL, tables, constraints, etc. Believe it or not it's SUPER simple stuff and, best of all, gives you a much greater sense of control. Also: _what's possible_. 
- use Node and a migration framework that works independently. In fact you could use Ecto if you wanted to build your tables out. I've been bugging Jose to release Ecto's migrations independently

**Comment by CrowdHailer** [comment]
Thanks for the feed back.

I have knuckled down and spent the day getting to know SQL, fortunately I have wanted to a little while and this was a good final push.

Still feel like a super welcoming README might have a space for a few lines on the topic of creating those tables for those that are in a rush. But if you disagree well I will happily differ to your decision on that.

**Comment by robconery** [comment]
That sounds good to me :). If you'd like to PR such a thing it would be extremely helpful :).
