### ISSUE TITLE
Does Moebius sanitize user input?

### ISSUE THREAD

**Issue by jordelver** [robconery/moebius#71]
In order to work around [this](https://github.com/robconery/moebius/issues/64) I'm piping SQL directly to the database like this: 

``` elixir
def update_movie(release_date, movie) do
  "UPDATE movies SET release_date = '#{format_date(release_date)}' WHERE original_title = '#{movie.original_title}';"
  |> LetterboxdCal.Db.run
end
```

It was then pointed out to me that this is susceptible to SQL injection as the data is user supplied. 

Does Moebius do anything to sanitise user data or is up to me do handle that? I looked through the code base and I couldn't see anything which looked like it handled that.

Thanks.

**Comment by robconery** [comment]
Sorry for the quick answer - I just saw the first line where you were having date issues ... thus the query here. Yes, this is ripe for SQL Injection, no Moebius won't rewrite the SQL statement as you've written it here. What you need to do is to pass the dates as parameters if the user can ever touch the date parameters.

So, this should work:

``` elixir
def update_movie(release_date, movie) do
  "UPDATE movies SET release_date = $1 WHERE original_title =$2;"
  |> LetterboxdCal.Db.run([format_date(release_date,movie.original_title]),
end
```

**Comment by robconery** [comment]
I should expand a bit here - we leave sanitizing stuff to the driver - I wouldn't trust myself to write such a thing :). You can have a look through our tests here:
https://github.com/robconery/moebius/blob/master/test/moebius/update_test.exs

Also: @nurugger07 just pushed a bunch of date stuff to master so if you wanted you can switch your dependency to this repo to get the latest bits, which might help with the date problems you're having.

**Comment by jordelver** [comment]
Thanks for the response @robconery 

> So, this should work:
> 
> def update_movie(release_date, movie) do
>    "UPDATE movies SET release_date = $1 WHERE original_title = $2;"
>    |> LetterboxdCal.Db.run([format_date(release_date), movie.original_title])
> end

I tried this but it doesn't work unfortunately. I get the same data related error as in my [previous issue](https://github.com/robconery/moebius/issues/64).

> I should expand a bit here - we leave sanitizing stuff to the driver - I wouldn't trust myself to write such a thing :). You can have a look through our tests here:
> https://github.com/robconery/moebius/blob/master/test/moebius/update_test.exs

Cool, thanks. Good to know that's happening at the driver level :) I had a look at the tests but they all show using the filter form, not the raw SQL form, but I do understand that I should be using the parameters 👍 

> Also: @nurugger07 just pushed a bunch of date stuff to master so if you wanted you can switch your dependency to this repo to get the latest bits, which might help with the date problems you're having.

I can't see any of this?

**Comment by robconery** [comment]
Hmm - I had thought he committed the changes he was working on. Damn. I'm going to close this issue and see if I can get a fix pushed for the other one.

Dates... grr....

**Comment by jordelver** [comment]
Thank you. I appreciate your work on this 👍
