### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by acrolink** [robconery/moebius#72]
```
exited in: :gen_server.call(Moebius.Db, {:checkout, #Reference<0.0.2.13839>, true, 15000}, 5000) ** (EXIT) no process
```

What this means? Thanks.

**Comment by robconery** [comment]
It means that Moebius isn't started. The README has details on how to do this, but it's hard to know what you're trying to do without seeing more code.

**Comment by acrolink** [comment]
Thank you @robconery

**Comment by kevin-DL** [comment]
Hello. I have the same issue.
I get it when i try to run tests using the database. I think the configuration is Okay. It's in apps/domain.

https://github.com/kevin-DL/league/tree/feature/base-user

Can you direct me in the right direction?

Cheers,
Kevin

**Comment by robconery** [comment]
@kevin-DL  you've started Moebius as an application, but you now need to add a worker and add it to your supervision tree. Read the "Supervision and Databases" section and it should work for you. If it doesn't, please open a separate issue with some more details.

**Comment by kevin-DL** [comment]
@robconery Thank you, that was what i needed.
Cheers,
Kevin

**Comment by halla** [comment]
Maybe include a note in the readme about putting

`worker(Moebius.Db, [Moebius.get_connection])
`

in the application file? The mention of starting the worker is in the "You don't need to do any of this " -section. :)

**Comment by robconery** [comment]
I believe that's just a bolded statement, not a section. The section is "Supervision and Databases" and honestly I don't know how I can make the whole thing clearer... but I'm open to any suggestions. If you feel like giving it a shot, I would appreciate it :).

**Comment by halla** [comment]
Maybe the "you can supervise each independently, or not at all. " added to the confusion as I took it to mean that I don't necessarily need a worker to get started...

**Comment by robconery** [comment]
Hmm - well that should be the case. If you start Moebius as an app in your mix file you should have access to the default database... I hope. I believe [this code](https://github.com/robconery/moebius/blob/master/lib/moebius.ex#L1) is still being called, at least.

**Comment by halla** [comment]
There doesn't seem to be an application callback defined  (no mod -option given in the moebius mix-file), so the code code is loaded but start/2 is not called automatically.

**Comment by robconery** [comment]
Ah - did that change, I wonder, in 1.3? Hmmm. If you're up for a PR I'd hug you :)

**Comment by halla** [comment]
Just making it to start automatically would mean that  it starts for those with custom setup as well, I guess? I'll practice with a readme-pr first...
