### ISSUE TITLE
run_with_psql doesn't use the configured connection info

### ISSUE THREAD

**Issue by maxim** [robconery/moebius#77]
I have postgres setup in docker, via tcp, but when I call `run_with_psql` it attempts to connect to a socket. Looking at the command, it seems that it never uses host/port stuff I configured. Wonder if this is intentional?

**Comment by xivSolutions** [comment]
Yeah, at the moment the `run_with_psql` function basically assumes a local database. It would be a simple thing to add additional function signatures to match on the additional arguments needed for the host/port stuff. 

Unless @robconery or @nurugger07 have something to say to the contrary, you are more than welcome to put in a PR, or if not, I can add something this weekend. 

Feel up for it?

**Comment by maxim** [comment]
@xivSolutions You're right, and I wouldn't mind doing it. I realize however that there might be more to this story. If postgres is in docker, and psql is on the host (mac), it's likely their versions are mismatched, and this command shouldn't assume that simply calling `psql` will do the right thing. This makes it a bit more involved.

**Comment by robconery** [comment]
Added this for v3.
