### ISSUE TITLE
Transformer atomizer is only a single level traversal

### ISSUE THREAD

**Issue by robconery** [robconery/moebius#8]
How's that for a title? Currently the result map from the database comes back with string keys and I wrote a hackey thing to `coerce_atoms` for dot notation. This only does a comprehension on the root keys - it won't go any deeper which, in the case of a regular query, is fine. When we move to doing more document stuff (`jsonb`), however, we'll want this.

**Comment by nurugger07** [comment]
@robconery removed `coerce_atoms/1` in favor of `to_map/2`. We can now handle multi-level traversal.

**Comment by robconery** [comment]
Huzzah!

**Comment by robconery** [comment]
Push this and we'll rev to 1.0.4

**Comment by nurugger07** [comment]
It's on master now

**Comment by nurugger07** [comment]
Gonna go ahead and close this since it's in the latest release
