### ISSUE TITLE
Updating array column:

### ISSUE THREAD

**Issue by fazibear** [robconery/moebius#80]
When trying to update array column:
```elixir
Moebius.Query.db(:users)
  |> Moebius.Query.filter(email: "admin@wp.pl") 
  |> Moebius.Query.update(roles: ["admin"]) 
  |> App.Db.query
```

got exception:

```
** (ArgumentError) Postgrex expected a list that can be encoded/cast to type "_varchar", got "admin". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
         (postgrex) lib/postgrex/extensions/array.ex:11: Postgrex.Extensions.Array.encode/4
         (postgrex) lib/postgrex/query.ex:135: DBConnection.Query.Postgrex.Query.do_encode/4
         (postgrex) lib/postgrex/query.ex:72: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection) lib/db_connection.ex:859: DBConnection.describe_execute/4
    (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:921: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
         (postgrex) lib/postgrex.ex:125: Postgrex.query/4
```

**Comment by robconery** [comment]
This is a Postgres encoding error, as you can see. You can try setting the value to a string, as Postgrex has recommended, and see if that works out.

**Comment by fazibear** [comment]
It's not a postgrex problem: https://github.com/fazibear/moebius/commit/e8ea2430ac33adf6bfb7be26e9edcb50c6d09644

**Comment by robconery** [comment]
This is a diff and doesn't explain anything to me. I can *guess* as to what you mean or you can simply tell me, which I would prefer. Keep in mind I have 10 other things that are occupying my mind and I'm dropping back into this issue after 30 days of not thinking about it once. I'd like to see if we can minimize the back and forth.

**Comment by fazibear** [comment]
Sorry, I just showed you how I make it work in my fork. Here we have a problem with building params for query. In this example:

```elixir
Moebius.Query.db(:users)
  |> Moebius.Query.filter(email: "admin@wp.pl") 
  |> Moebius.Query.update(title: "test", roles: ["admin", "other"]) 
  |> App.Db.query
```
params hash looks like this: `["admin@wp.pl", "test", "admin", "other"]`, witch is bad. It should look like: `["admin@wp.pl", "test", ["admin", "other"]]`.  This is what `List.flatten` do. And it's not good in that place.

**Comment by robconery** [comment]
I understand that it solves your problem :). We put it there for a reason - what would be interesting is to know how the test suite behaves when running with your changes. I'd also like to know if my original suggestion of passing in a string works for you.

**Comment by fazibear** [comment]
You mean like this ?
```elixir
Moebius.Query.db(:users)
  |> Moebius.Query.filter(email: "admin@wp.pl") 
  |> Moebius.Query.update(title: "test", roles: "['admin', 'other']") 
  |> App.Db.query
```
No it's not work, same error.

**Comment by robconery** [comment]
Yeah - bummer. I know I put the flatten statement in there to deal with the way parameters are passed in some cases. It would help if you ran test suite against your change so I could see what breaks.

**Comment by robconery** [comment]
Found the problem - thanks for the code :). Will be fixed with v3.
