### ISSUE TITLE
readme talks about existence operator, but doesn't show it?

### ISSUE THREAD

**Issue by Trevoke** [robconery/moebius#81]
This is the code example for the existence operator:

```elixir
buddies = db(:friends)
  |> exists(:tags, "best")
  |> Moebius.Db.run
```

Where should the `?` go?

**Comment by robconery** [comment]
I don't understand the question nor the problem - can you be a bit more clear?

**Comment by Trevoke** [comment]
The readme says there is `?` as existence operator. It then shows a code example that does not have a question mark. Does that mean there is no existence operator and the readme was making a philosophical statement?

**Comment by robconery** [comment]
The existence operator for PostgreSQL JSON/JSONB  is `?`. We abstract that whole thing so you can just call `exists`:

https://github.com/robconery/moebius/blob/master/lib/moebius/document_query.ex#L140

Does that make sense?

**Comment by Trevoke** [comment]
Ah yep. Now I understand.
