### ISSUE TITLE
`pool_mod` option does not work

### ISSUE THREAD

**Issue by fazibear** [robconery/moebius#86]
I'm trying to use Moebius with pool, but it won't work.

First of all, `pool_mod` does nothing, as I read from postgrex docs it should be a `pool` key. 

When I change config to use `pool` key, i go weird exception:

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
        :invalid_message.exception([])
        (db_connection) lib/db_connection.ex:925: DBConnection.checkout/2
        (db_connection) lib/db_connection.ex:741: DBConnection.run/3
        (db_connection) lib/db_connection.ex:1132: DBConnection.run_meter/3
        (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
        (postgrex) lib/postgrex.ex:125: Postgrex.query/4
        (moebius) lib/moebius/database.ex:236: Moebius.Database.execute/1
```

noticed that this exception also appears with postgrex:

```
iex(5)> {:ok, pid} = Postgrex.start_link(hostname: "localhost", database: "taped_dev", pool: DBConnection.Poolboy)
{:ok, #PID<0.350.0>}
iex(6)> Postgrex.query!(pid, "SELECT * FROM users", [])
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
                    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:925: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:741: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1132: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (db_connection) lib/db_connection.ex:600: DBConnection.prepare_execute!/4
         (postgrex) lib/postgrex.ex:146: Postgrex.query!/4
```

And solution is simple, we need to execute query with pool: config:

```
Postgrex.query!(pid, "SELECT * FROM users", [],  pool: DBConnection.Poolboy)
```

This patches works for me: https://github.com/fazibear/moebius/commit/07c94cb4d3fca03f0f687de1135343b27039d8ef https://github.com/fazibear/moebius/commit/c494becbf1ffe7d12848ef414a5cc32a3dac2d47

but is this a proper solution ?

Thanks

**Comment by fishcakez** [comment]
`pool` must always be passed to Postgrex calls if not using the default pool.

**Comment by fazibear** [comment]
That's right. Only default connection works. If you want to run a `DBConnection.Poolboy` you need code changes. Examples from readme will not work. They will connect to your DB with only one connection.

**Comment by robconery** [comment]
Hmm - didn't know about this change.

**Comment by fishcakez** [comment]
> Hmm - didn't know about this change.

This has been the case since `DBConnection` was introduced.

**Comment by robconery** [comment]
Oh wow - WTH then. That's... disturbing. Thanks James :).

**Comment by fishcakez** [comment]
> Oh wow - WTH then. That's... disturbing. Thanks James :).

At least for tagged releases of postgrex..

**Comment by robconery** [comment]
Given that Postgrex now uses db_connection, what do I have to do here? I'm a bit lost.

**Comment by fishcakez** [comment]
The DBConnection/Postgrex pooling is very much designed around Ecto so I
think it can be a little awkward for anything that doesnt behave exactly
how Ecto does. The gist is that configuration is stored somewhere and it is
read on start_link/child_spec and on every transaction/query and passed as
options.

**Comment by robconery** [comment]
So... what you're basically saying is that the pooling we were using, which you recommended and Jose pushed me to use... is now essentially unavailable?

**Comment by fishcakez** [comment]
The pooling is available but it requires config to be passed on every
request. It might be the only issue is to rename `: pool_mod` to `: pool`.
`:pool_mod` has never been an option in a postgrex release.

**Comment by robconery** [comment]
This is now fixed - thanks for your help fishcakez - I think I misunderstood what you were saying which isn't surprising as I've been staring at this stuff too long.
