### ISSUE TITLE
Return values for IO actions

### ISSUE THREAD

**Issue by CrowdHailer** [robconery/moebius#90]
Not a big deal this one but I found some mentions to a possible need to support a v3.

As far as I'm aware the convention for functions that fail is to return `{:ok, value}` or `{:error, reason}`. At the moment `Moebius.Db.run(query)` (and a few others) doesn't put successful return values in an :ok tuple.

Would it be something that would be acceptable to change for a major update?

As I have the convention of putting successful paths first I keep having to pattern match on some contents of the result. 

```elixir
    case MyDb.run(action) do
      record = %{id: ^id} ->
        {:ok, unpack(record)}
      {:error, reason} ->
        {:error, reason}
    end
```

Certainly not the end of the world, for sure.

**Comment by robconery** [comment]
When I first wrote the lib that convention was being debated. I think it's just the way you do it in Erlang, which makes, sense, but some Elixirists were saying (I think rightly) that the existence of `{:error, x}` means there's an error. If it's not there, it's `{:ok}` by definition. That's what I went with as it makes life easier.

You can still match on your result in your code - but I do understand where you're coming from. Also: Ecto does this so we might as well have parity with our Elixir overlords :).

I'm on this now...

**Comment by CrowdHailer** [comment]
I'm pleased you decided to go this way. I feel that ever since I released my [OK](https://github.com/crowdhailer/ok) library, I have rather adopted it as a mission
